# Asssignment 1

Evaluate the dataset of the Summer Olympics, London 2012 to:

•	Find and print the name of the country that won maximum gold medals

In [25]:
import pandas as pd
pd.DataFrame({'id':[100, 101, 102], 'color':['red', 'blue', 'red']})
country = pd.DataFrame({'CountryName':['India', 'China' , 'India' , 'China', 'Germany', 'India' , 'India'],'Medals':['Gold', 'Silver', 'Gold', 'Gold', 'Gold', 'Gold', 'Gold']})
country

  CountryName  Medals
0       India    Gold
1       China  Silver
2       India    Gold
3       China    Gold
4     Germany    Gold
5       India    Gold

In [50]:
country.loc[country.Medals=='Gold', :]

  CountryName Medals
0       India   Gold
2       India   Gold
3       China   Gold
4     Germany   Gold
5       India   Gold

•	Find and print the countries who won more than 20 gold medals,

In [62]:
country.loc[: , 'CountryName'].apply([x if x in 'Medals'='Gold'])

             Medals
CountryName
China             2
Germany           1
India             3

# Assignment 2

You have been provided with a dataset that lists Ohio State’s leading causes of death from the year 2012.

Using the two data points: 
•	Cause of deaths and
•	Percentile
Draw a pie chart to visualize the dataset.

In [14]:
import pandas as pd
ohio = pd.DataFrame({'Causesofdeaths':[0, 1, 3, 4, 5, 6, 7], 'Percentile':[62, 1,5, 4, 2, 1, 26, 2]})

ValueError: arrays must all be same length

# Assignment 3

Analyze the Federal Aviation Authority (FAA) dataset using Pandas to do the following:

1.	View 
    a.	aircraft make name
    b.	state name
    c.	aircraft model name
    d.	text information
    e.	flight phase
    f.	event description type
    g.	fatal flag

In [3]:
import pandas as pd

In [4]:
faa = pd.read_csv("C:/Intellipaat_python_for_datascience/lecture 6/faa_ai_prelim.csv")

In [5]:
faa.head()

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
faa.describe()

,ACFT_MISSING_FLAG,FAR_PART,FLT_CRW_INJ_NONE,FLT_CRW_INJ_MINOR,FLT_CRW_INJ_SERIOUS,FLT_CRW_INJ_FATAL,FLT_CRW_INJ_UNK,CBN_CRW_INJ_NONE,CBN_CRW_INJ_MINOR,CBN_CRW_INJ_SERIOUS,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
count,0.0,1.0,64.000000,6.000000,1.0,8.000000,0.0,0.0,0.0,0.0,...,17.000000,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
mean,NaN,91.0,1.218750,1.333333,3.0,1.500000,NaN,NaN,NaN,NaN,...,1.823529,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
std,NaN,NaN,0.700765,0.516398,NaN,0.534522,NaN,NaN,NaN,NaN,...,1.236694,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,91.0,1.000000,1.000000,3.0,1.000000,NaN,NaN,NaN,NaN,...,1.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
25%,NaN,91.0,1.000000,1.000000,3.0,1.000000,NaN,NaN,NaN,NaN,...,1.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
50%,NaN,91.0,1.000000,1.000000,3.0,1.500000,NaN,NaN,NaN,NaN,...,2.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
75%,NaN,91.0,1.000000,1.750000,3.0,2.000000,NaN,NaN,NaN,NaN,...,2.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
max,NaN,91.0,6.000000,2.000000,3.0,2.000000,NaN,NaN,NaN,NaN,...,6.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0

In [7]:
faa.columns

Index(['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME', 'LOC_CNTRY_NAME', 'RMK_TEXT',
       'EVENT_TYPE_DESC', 'FSDO_DESC', 'REGIST_NBR', 'FLT_NBR', 'ACFT_OPRTR',
       'ACFT_MAKE_NAME', 'ACFT_MODEL_NAME', 'ACFT_MISSING_FLAG',
       'ACFT_DMG_DESC', 'FLT_ACTIVITY', 'FLT_PHASE', 'FAR_PART', 'MAX_INJ_LVL',
       'FATAL_FLAG', 'FLT_CRW_INJ_NONE', 'FLT_CRW_INJ_MINOR',
       'FLT_CRW_INJ_SERIOUS', 'FLT_CRW_INJ_FATAL', 'FLT_CRW_INJ_UNK',
       'CBN_CRW_INJ_NONE', 'CBN_CRW_INJ_MINOR', 'CBN_CRW_INJ_SERIOUS',
       'CBN_CRW_INJ_FATAL', 'CBN_CRW_INJ_UNK', 'PAX_INJ_NONE', 'PAX_INJ_MINOR',
       'PAX_INJ_SERIOUS', 'PAX_INJ_FATAL', 'PAX_INJ_UNK', 'GRND_INJ_NONE',
       'GRND_INJ_MINOR', 'GRND_INJ_SERIOUS', 'GRND_INJ_FATAL', 'GRND_INJ_UNK'],
      dtype='object')

In [8]:
faa['ACFT_MAKE_NAME']

0                   BEECH
1                    VANS
2                  CESSNA
3                 LANCAIR
4                  CESSNA
5                    BELL
6                   PIPER
7                  CESSNA
8                  BOEING
9                     NaN
10                 CESSNA
11                    NaN
12                 CESSNA
13                 CESSNA
14                  BEECH
15                 CESSNA
16               CHRISTEN
17                  PIPER
18                  PIPER
19                 CESSNA
20                 HUGHES
21                 CESSNA
22                    NaN
23                 BOEING
24                  GLOBE
25                  PIPER
26            GREAT LAKES
27                 CESSNA
28    CONSOLIDATED VULTEE
29                 CESSNA
             ...
53                  PIPER
54                 CESSNA
55          FLIGHT DESIGN
56                  PIPER
57                    NaN
58                    NaN
59                  PIPER
60                  PIPER
61                  BEECH
62                  BEECH
63                 CESSNA
64                 CESSNA
65                 CESSNA
66                  PIPER
67                LANCAIR
68                  BEECH
69                 MOONEY
70         AERO COMMANDER
71                 CESSNA
72                 MOONEY
73                  BEECH
74             SABRELINER
75                 MOONEY
76                  PIPER
77                 BOEING
78                AERONCA
79         NORTH AMERICAN
80               CHAMPION
81                  BEECH
82                 CESSNA
Name: ACFT_MAKE_NAME, Length: 83, dtype: object

In [9]:
faa.LOC_STATE_NAME

0     North Carolina
1            Florida
2         New Jersey
3     North Carolina
4             Alaska
5             Hawaii
6            Florida
7            Florida
8            Florida
9            Florida
10          Virginia
11           Arizona
12          New York
13         Louisiana
14        California
15           Florida
16         Louisiana
17          Missouri
18           Florida
19             Texas
20     West Virginia
21             Texas
22           Arizona
23          Michigan
24          Colorado
25         Tennessee
26        California
27     New Hampshire
28        California
29          Colorado
           ...
53           Florida
54      South Dakota
55        California
56           Florida
57             Idaho
58        California
59           Arizona
60      Pennsylvania
61        California
62           Arizona
63            Oregon
64           Montana
65            Oregon
66      Rhode Island
67            Kansas
68           Florida
69              Ohio
70          Virginia
71           Georgia
72          Maryland
73        California
74          Arkansas
75          Maryland
76            Kansas
77             Texas
78             Texas
79           Arizona
80        California
81        California
82           Alabama
Name: LOC_STATE_NAME, Length: 83, dtype: object

In [10]:
faa['ACFT_MODEL_NAME']

0           36
1          RV7
2          172
3          235
4          172
5          206
6         PA24
7          210
8          747
9          NaN
10         172
11     FIREFLY
12         310
13         210
14         T34
15         152
16    EAGLE II
17        PA34
18        PA28
19         150
20         369
21         210
22         NaN
23         737
24        GC1B
25        PA20
26        2T1A
27         560
28        BT15
29         210
        ...
53        PA28
54         150
55        CTLS
56        PA34
57      KITFOX
58         NaN
59        PA28
60        PA34
61          36
62          33
63         206
64         206
65         175
66        PA31
67          IV
68          35
69        M20K
70         500
71         310
72        M20E
73          35
74       NA265
75        M20K
76        PA24
77         737
78        O58B
79         F51
80       8KCAB
81          35
82         182
Name: ACFT_MODEL_NAME, Length: 83, dtype: object

In [11]:
faa['RMK_TEXT']

0     AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...
1     AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...
2     AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...
3     AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...
4     AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...
5     N80918 BELL 206B ROTORCRAFT CRASHED INTO THE W...
6     AIRCRAFT GEAR COLLAPSED ON LANDING, BROOKSVILL...
7     AIRCRAFT ON LANDING GEAR COLLAPSED, WINTER HAV...
8     N859GT ATLAS AIR FLIGHT GTI33 BOEING 747 AIRCR...
9     AIRCRAFT, LSA PARADISE P1,  ON LANDING NOSE GE...
10    AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...
11    N2194X FIREFLY 9 BALLOON, ON LANDING STRUCK TH...
12       AIRCRAFT GEAR COLLAPSED ON LANDING, ELMIRA, NY
13    AIRCRAFT ON LANDING NOSE GEAR COLLAPSED, LAKEF...
14    AIRCRAFT ON TAKEOFF STRUCK RUNWAY LIGHT AT THE...
15    AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR PEMBR...
16    AIRCRAFT ON TAKEOFF WENT OFF THE GRASS STRIP A...
17    AIRCRAFT ON LANDING GEAR COLLAPSED, SPRINGFIEL...
18    AIRCRAFT ON DEPARTURE STRUCK A BIRD, RETURNED ...
19    AIRCRAFT ON LANDING WENT OFF THE RUNWAY, THROU...
20    N1107T HUGHES 369D ROTORCRAFT MADE A PRECAUTIO...
21    AIRCRAFT FORCE LANDED IN A FIELD 2 MILES FROM ...
22    AIRCRAFT, LIGHT SPORT EVOLUTION REVO,  ON TAKE...
23    AMERICAN AIRLINES FLIGHT AAL1241 BOEING 737 AI...
24    AIRCRAFT LANDED AND THE GEAR COLLAPSED, CENTEN...
25    AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR DAYTO...
26    AIRCRAFT ON LANDING TIPPED ONTO ITS NOSE, PALO...
27    N70TH DELTA PRIVATE JET FLIGHT DPJ70 CESSNA C5...
28    AIRCRAFT ON TAXI STRUCK A PARKED AIRCRAFT, CHI...
29                 AIRCRAFT LANDED GEAR UP, DURANGO, CO
                            ...
53    AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...
54    AIRCRAFT ON TAXI, PROP STRUCK THE GROUND, STUR...
55    AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...
56    HK4699G COLUMBIA REGISTRATION, PIPER PA34 AIRC...
57    AIRCRAFT ON LANDING GEAR COLLAPSED, HELLS CANY...
58    AIRCRAFT, LIGHT SPORT DOVA AS SKYLARK,  ON LAN...
59    AIRCRAFT LANDED AND WENT OFF THE END OF THE RU...
60    AIRCRAFT ON APPROACH TO LAND, STRUCK TREES, LA...
61    AIRCRAFT FORCE LANDED IN THE WETLAND/SLOUGH AR...
62    AIRCRAFT ON TAKEOFF, STRUCK A BIRD, RETURNED A...
63      AIRCRAFT ON LANDING, GEAR COLLAPSED, EUGENE, OR
64    AIRCRAFT ON LANDING, GEAR COLLAPSED AND STRUCK...
65    AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...
66    AIRCRAFT ON LANDING STRUCK A BIRD, MIDDLETOWN, RI
67    AIRCRAFT DURING FLIGHT, WINDOW SEPARATED FROM ...
68    AIRCRAFT ON LANDING, NOSE GEAR COLLASPED, CRYS...
69    AIRCRAFT ON LANDING, GEAR COLLAPSED, DEFIANCE, OH
70    AIRCRAFT ON TAXI, GEAR RETRACTED, CHESAPEAKE,  VA
71     AIRCRAFT ON LANDING, GEAR COLLAPSED, GRIFFIN, GA
72    AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...
73    AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, MONT...
74    AIRCRAFT ON LANDING, GEAR COLLAPSED, WEST MEMP...
75    AIRCRAFT ON LANDING, STRUCK A SIGN AND RUNWAY ...
76                  AIRCRAFT LANDED GEAR UP, EUREKA, KS
77    SOUTHWEST AIRLINES FLIGHT SWA3817 BOEING 737 A...
78    AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...
79    AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...
80    N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...
81    N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...
82    N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...
Name: RMK_TEXT, Length: 83, dtype: object

In [12]:
faa.loc[:,['ACFT_MAKE_NAME','LOC_STATE_NAME','ACFT_MODEL_NAME','RMK_TEXT','FLT_PHASE','EVENT_TYPE_DESC','FATAL_FLAG']]

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,NaN
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,NaN
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,NaN
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,NaN
5,BELL,Hawaii,206,N80918 BELL 206B ROTORCRAFT CRASHED INTO THE W...,UNKNOWN (UNK),Accident,NaN
6,PIPER,Florida,PA24,"AIRCRAFT GEAR COLLAPSED ON LANDING, BROOKSVILL...",LANDING (LDG),Incident,NaN
7,CESSNA,Florida,210,"AIRCRAFT ON LANDING GEAR COLLAPSED, WINTER HAV...",LANDING (LDG),Incident,NaN
8,BOEING,Florida,747,N859GT ATLAS AIR FLIGHT GTI33 BOEING 747 AIRCR...,TAKEOFF (TOF),Incident,NaN
9,NaN,Florida,NaN,"AIRCRAFT, LSA PARADISE P1, ON LANDING NOSE GE...",LANDING (LDG),Incident,NaN
10,CESSNA,Virginia,172,AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...,LANDING (LDG),Incident,NaN
11,NaN,Arizona,FIREFLY,"N2194X FIREFLY 9 BALLOON, ON LANDING STRUCK TH...",LANDING (LDG),Incident,NaN
12,CESSNA,New York,310,"AIRCRAFT GEAR COLLAPSED ON LANDING, ELMIRA, NY",LANDING (LDG),Incident,NaN
13,CESSNA,Louisiana,210,"AIRCRAFT ON LANDING NOSE GEAR COLLAPSED, LAKEF...",LANDING (LDG),Incident,NaN
14,BEECH,California,T34,AIRCRAFT ON TAKEOFF STRUCK RUNWAY LIGHT AT THE...,TAKEOFF (TOF),Incident,NaN
15,CESSNA,Florida,152,"AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR PEMBR...",LANDING (LDG),Incident,NaN
16,CHRISTEN,Louisiana,EAGLE II,AIRCRAFT ON TAKEOFF WENT OFF THE GRASS STRIP A...,TAKEOFF (TOF),Accident,NaN
17,PIPER,Missouri,PA34,"AIRCRAFT ON LANDING GEAR COLLAPSED, SPRINGFIEL...",LANDING (LDG),Incident,NaN
18,PIPER,Florida,PA28,"AIRCRAFT ON DEPARTURE STRUCK A BIRD, RETURNED ...",TAKEOFF (TOF),Incident,NaN
19,CESSNA,Texas,150,"AIRCRAFT ON LANDING WENT OFF THE RUNWAY, THROU...",LANDING (LDG),Incident,NaN
20,HUGHES,West Virginia,369,N1107T HUGHES 369D ROTORCRAFT MADE A PRECAUTIO...,LANDING (LDG),Incident,NaN
21,CESSNA,Texas,210,AIRCRAFT FORCE LANDED IN A FIELD 2 MILES FROM ...,UNKNOWN (UNK),Accident,NaN
22,NaN,Arizona,NaN,"AIRCRAFT, LIGHT SPORT EVOLUTION REVO, ON TAKE...",TAKEOFF (TOF),Accident,Yes
23,BOEING,Michigan,737,AMERICAN AIRLINES FLIGHT AAL1241 BOEING 737 AI...,TAXI (TXI),Incident,NaN
24,GLOBE,Colorado,GC1B,"AIRCRAFT LANDED AND THE GEAR COLLAPSED, CENTEN...",LANDING (LDG),Incident,NaN
25,PIPER,Tennessee,PA20,"AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR DAYTO...",LANDING (LDG),Incident,NaN
26,GREAT LAKES,California,2T1A,"AIRCRAFT ON LANDING TIPPED ONTO ITS NOSE, PALO...",LANDING (LDG),Incident,NaN
27,CESSNA,New Hampshire,560,N70TH DELTA PRIVATE JET FLIGHT DPJ70 CESSNA C5...,TAXI (TXI),Incident,NaN
28,CONSOLIDATED VULTEE,California,BT15,"AIRCRAFT ON TAXI STRUCK A PARKED AIRCRAFT, CHI...",TAXI (TXI),Incident,NaN
29,CESSNA,Colorado,210,"AIRCRAFT LANDED GEAR UP, DURANGO, CO",LANDING (LDG),Incident,NaN
...,...,...,...,...,...,...,...
53,PIPER,Florida,PA28,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,UNKNOWN (UNK),Accident,Yes
54,CESSNA,South Dakota,150,"AIRCRAFT ON TAXI, PROP STRUCK THE GROUND, STUR...",TAXI (TXI),Accident,NaN
55,FLIGHT DESIGN,California,CTLS,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,UNKNOWN (UNK),Accident,Yes
56,PIPER,Florida,PA34,"HK4699G COLUMBIA REGISTRATION, PIPER PA34 AIRC...",LANDING (LDG),Incident,NaN
57,NaN,Idaho,KITFOX,"AIRCRAFT ON LANDING GEAR COLLAPSED, HELLS CANY...",LANDING (LDG),Incident,NaN
58,NaN,California,NaN,"AIRCRAFT, LIGHT SPORT DOVA AS SKYLARK, ON LAN...",LANDING (LDG),Incident,NaN
59,PIPER,Arizona,PA28,AIRCRAFT LANDED AND WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,NaN
60,PIPER,Pennsylvania,PA34,"AIRCRAFT ON APPROACH TO LAND, STRUCK TREES, LA...",APPROACH (APR),Accident,NaN
61,BEECH,California,36,AIRCRAFT FORCE LANDED IN THE WETLAND/SLOUGH AR...,LANDING (LDG),Accident,NaN
62,BEECH,Arizona,33,"AIRCRAFT ON TAKEOFF, STRUCK A BIRD, RETURNED A...",TAKEOFF (TOF),Incident,NaN
63,CESSNA,Oregon,206,"AIRCRAFT ON LANDING, GEAR COLLAPSED, EUGENE, OR",LANDING (LDG),Incident,NaN
64,CESSNA,Montana,206,"AIRCRAFT ON LANDING, GEAR COLLAPSED AND STRUCK...",LANDING (LDG),Accident,NaN
65,CESSNA,Oregon,175,AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...,LANDING (LDG),Accident,NaN
66,PIPER,Rhode Island,PA31,"AIRCRAFT ON LANDING STRUCK A BIRD, MIDDLETOWN, RI",LANDING (LDG),Incident,NaN
67,LANCAIR,Kansas,IV,"AIRCRAFT DURING FLIGHT, WINDOW SEPARATED FROM ...",UNKNOWN (UNK),Incident,NaN
68,BEECH,Florida,35,"AIRCRAFT ON LANDING, NOSE GEAR COLLASPED, CRYS...",LANDING (LDG),Incident,NaN
69,MOONEY,Ohio,M20K,"AIRCRAFT ON LANDING, GEAR COLLAPSED, DEFIANCE, OH",LANDING (LDG),Incident,NaN
70,AERO COMMANDER,Virginia,500,"AIRCRAFT ON TAXI, GEAR RETRACTED, CHESAPEAKE, VA",TAXI (TXI),Incident,NaN
71,CESSNA,Georgia,310,"AIRCRAFT ON LANDING, GEAR COLLAPSED, GRIFFIN, GA",LANDING (LDG),Incident,NaN
72,MOONEY,Maryland,M20E,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,NaN
73,BEECH,California,35,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, MONT...",LANDING (LDG),Incident,NaN
74,SABRELINER,Arkansas,NA265,"AIRCRAFT ON LANDING, GEAR COLLAPSED, WEST MEMP...",LANDING (LDG),Incident,NaN
75,MOONEY,Maryland,M20K,"AIRCRAFT ON LANDING, STRUCK A SIGN AND RUNWAY ...",LANDING (LDG),Incident,NaN
76,PIPER,Kansas,PA24,"AIRCRAFT LANDED GEAR UP, EUREKA, KS",LANDING (LDG),Incident,NaN
77,BOEING,Texas,737,SOUTHWEST AIRLINES FLIGHT SWA3817 BOEING 737 A...,NaN,Incident,NaN
78,AERONCA,Texas,O58B,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",LANDING (LDG),Accident,NaN
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Accident,Yes

2. Clean the dataset and replace the fatal flag NaN with “No”

In [19]:
faa['FATAL_FLAG'].fillna('No' , inplace = True)

In [21]:
faa[:]

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,No,19-FEB-16,18-FEB-16,20:23:00Z,PEARL HARBOR,Hawaii,NaN,N80918 BELL 206B ROTORCRAFT CRASHED INTO THE W...,Accident,FAA Honolulu FSDO-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,No,18-FEB-16,17-FEB-16,21:15:00Z,BROOKSVILLE,Florida,NaN,"AIRCRAFT GEAR COLLAPSED ON LANDING, BROOKSVILL...",Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,No,18-FEB-16,17-FEB-16,18:10:00Z,WINTER HAVEN,Florida,NaN,"AIRCRAFT ON LANDING GEAR COLLAPSED, WINTER HAV...",Incident,FAA Orlando FSDO-15,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,No,18-FEB-16,17-FEB-16,13:50:00Z,MIAMI,Florida,NaN,N859GT ATLAS AIR FLIGHT GTI33 BOEING 747 AIRCR...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,No,18-FEB-16,17-FEB-16,15:30:00Z,FERNANDINA BEACH,Florida,NaN,"AIRCRAFT, LSA PARADISE P1, ON LANDING NOSE GE...",Incident,FAA Orlando FSDO-15,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,No,18-FEB-16,17-FEB-16,15:40:00Z,NEWPORT NEWS,Virginia,NaN,AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...,Incident,FAA Richmond FSDO-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,No,17-FEB-16,15-FEB-16,16:12:00Z,PHOENIX,Arizona,NaN,"N2194X FIREFLY 9 BALLOON, ON LANDING STRUCK TH...",Incident,FAA Scottsdale FSDO-07,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,No,17-FEB-16,14-FEB-16,20:21:00Z,ELMIRA,New York,NaN,"AIRCRAFT GEAR COLLAPSED ON LANDING, ELMIRA, NY",Incident,FAA Rochester FSDO-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,No,17-FEB-16,14-FEB-16,02:00:00Z,NEW ORLEANS,Louisiana,NaN,"AIRCRAFT ON LANDING NOSE GEAR COLLAPSED, LAKEF...",Incident,FAA Baton Rouge FSDO-03,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,No,17-FEB-16,15-FEB-16,20:10:00Z,RIVERSIDE,California,NaN,AIRCRAFT ON TAKEOFF STRUCK RUNWAY LIGHT AT THE...,Incident,FAA Riverside FSDO-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,No,17-FEB-16,17-FEB-16,02:34:00Z,PEMBROOKE PINES,Florida,NaN,"AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR PEMBR...",Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,No,17-FEB-16,14-FEB-16,17:00:00Z,BELL CITY,Louisiana,NaN,AIRCRAFT ON TAKEOFF WENT OFF THE GRASS STRIP A...,Accident,FAA Baton Rouge FSDO-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,No,17-FEB-16,13-FEB-16,22:40:00Z,SPRINGFIELD,Missouri,NaN,"AIRCRAFT ON LANDING GEAR COLLAPSED, SPRINGFIEL...",Incident,FAA Kansas City FSDO-63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,No,17-FEB-16,16-FEB-16,18:40:00Z,VERO BEACH,Florida,NaN,"AIRCRAFT ON DEPARTURE STRUCK A BIRD, RETURNED ...",Incident,FAA Orlando FSDO-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,No,17-FEB-16,14-FEB-16,17:30:00Z,AUSTIN,Texas,NaN,"AIRCRAFT ON LANDING WENT OFF THE RUNWAY, THROU...",Incident,FAA San Antonio FSDO-17,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,No,17-FEB-16,15-FEB-16,17:53:00Z,CHARLESTON,West Virginia,NaN,N1107T HUGHES 369D ROTORCRAFT MADE A PRECAUTIO...,Incident,FAA Charleston FSDO-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,No,17-FEB-16,16-FEB-16,17:29:00Z,BENCHLEY,Texas,NaN,AIRCRAFT FORCE LANDED IN A FIELD 2 MILES FROM ...,Accident,FAA Houston FSDO-09,...,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,No,17-FEB-16,16-FEB-16,20:52:00Z,BUCKEYE,Arizona,NaN,"AIRCRAFT, LIGHT SPORT EVOLUTION REVO, ON TAKE...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,No,17-FEB-16,17-FEB-16,11:05:00Z,DETROIT,Michigan,NaN,AMERICAN AIRLINES FLIGHT AAL1241 BOEING 737 AI...,Incident,FAA East Michigan FSDO-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,No,16-FEB-16,12-FEB-16,15:22:00Z,DENVER,Colorado,NaN,"AIRCRAFT LANDED AND THE GEAR COLLAPSED, CENTEN...",Incident,FAA Denver FSDO-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,No,16-FEB-16,14-FEB-16,00:15:00Z,DAYTON,Tennessee,NaN,"AIRCRAFT FORCE LANDED ON A HIGHWAY, NEAR DAYTO...",Incident,FAA Nashville FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,No,16-FEB-16,13-FEB-16,23:19:00Z,PALO ALTO,California,NaN,"AIRCRAFT ON LANDING TIPPED ONTO ITS NOSE, PALO...",Incident,FAA San Jose FSDO-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,No,16-FEB-16,12-FEB-16,21:20:00Z,BERLIN,New Hampshire,NaN,N70TH DELTA PRIVATE JET FLIGHT DPJ70 CESSNA C5...,Incident,FAA Portland FSDO-65,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,No,16-FEB-16,13-FEB-16,23:01:00Z,CHINO,California,NaN,"AIRCRAFT ON TAXI STRUCK A PARKED AIRCRAFT, CHI...",Incident,FAA Riverside FSDO-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,No,16-FEB-16,13-FEB-16,17:45:00Z,DURANGO,Colorado,NaN,"AIRCRAFT LANDED GEAR UP, DURANGO, CO",Incident,FAA Salt Lake City FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,No,12-FEB-16,11-FEB-16,11:32:00Z,DESTIN,Florida,United States,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,Accident,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
54,No,11-FEB-16,10-FEB-16,16:40:00Z,STURGIS,South Dakota,NaN,"AIRCRAFT ON TAXI, PROP STRUCK THE GROUND, STUR...",Accident,FAA Rapid City FSDO-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,No,11-FEB-16,11-FEB-16,00:17:00Z,TULARE,California,NaN,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,Accident,FAA Fresno FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,No,10-FEB-16,09-FEB-16,21:11:00Z,PEMBROKE PINES,Florida,NaN,"HK4699G COLUMBIA REGISTRATION, PIPER PA34 AIRC...",Incident,FAA Miami FSDO-19,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,No,10-FEB-16,07-FEB-16,21:00:00Z,HELLS CANYON,Idaho,NaN,"AIRCRAFT ON LANDING GEAR COLLAPSED, HELLS CANY...",Incident,FAA Boise FSDO-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,No,10-FEB-16,09-FEB-16,21:46:00Z,PALO ALTO,California,NaN,"AIRCRAFT, LIGHT SPORT DOVA AS SKYLARK, ON LAN...",Incident,FAA San Jose FSDO-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,No,10-FEB-16,09-FEB-16,23:56:00Z,MESA,Arizona,NaN,AIRCRAFT LANDED AND WENT OFF THE END OF THE RU...,Incident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,No,10-FEB-16,09-FEB-16,11:30:00Z,WILLIAMSPORT,Pennsylvania,NaN,"AIRCRAFT ON APPROACH TO LAND, STRUCK TREES, LA...",Accident,FAA Harrisburg FSDO-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,No,09-FEB-16,09-FEB-16,02:00:00Z,SANTA BARBARA,California,NaN,AIRCRAFT FORCE LANDED IN THE WETLAND/SLOUGH AR...,Accident,FAA Van Nuys FSDO-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,No,09-FEB-16,08-FEB-16,18:22:00Z,GOODYEAR,Arizona,NaN,"AIRCRAFT ON TAKEOFF, STRUCK A BIRD, RETURNED A...",Incident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,No,09-FEB-16,08-FEB-16,00:00:00Z,EUGENE,Oregon,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, EUGENE, OR",Incident,FAA Portland FSDO-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,No,09-FEB-16,08-FEB-16,18:33:00Z,BILLINGS,Montana,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED AND STRUCK...",Accident,FAA Helena FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,No,09-FEB-16,08-FEB-16,18:58:00Z,GOLD BEACH,Oregon,NaN,AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...,Accident,FAA Portland FSDO-09,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,No,08-FEB-16,04-FEB-16,00:24:00Z,NEWPORT,Rhode Island,NaN,"AIRCRAFT ON LANDING STRUCK A BIRD, MIDDLETOWN, RI",Incident,FAA Boston FSDO-61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,No,08-FEB-16,05-FEB-16,19:45:00Z,GOODLAND,Kansas,NaN,"AIRCRAFT DURING FLIGHT, WINDOW SEPARATED FROM ...",Incident,FAA Wichita FSDO-64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,No,08-FEB-16,06-FEB-16,16:45:00Z,CRYSTAL RIVER,Florida,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLASPED, CRYS...",Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,No,08-FEB-16,06-FEB-16,21:45:00Z,DEFIANCE,Ohio,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, DEFIANCE, OH",Incident,FAA Columbus FSDO-07,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,No,08-FEB-16,05-FEB-16,07:30:00Z,CHESAPEAKE,Virginia,NaN,"AIRCRAFT ON TAXI, GEAR RETRACTED, CHESAPEAKE, VA",Incident,FAA Richmond FSDO-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,No,08-FEB-16,05-FEB-16,22:30:00Z,GRIFFIN,Georgia,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, GRIFFIN, GA",Incident,FAA Atlanta FSDO-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,No,08-FEB-16,07-FEB-16,19:21:00Z,GAITHERSBURG,Maryland,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Baltimore FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,No,08-FEB-16,05-FEB-16,20:54:00Z,MONTEREY,California,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, MONT...",Incident,FAA San Jose FSDO-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,No,08-FEB-16,06-FEB-16,22:00:00Z,WEST MEMPHIS,Arkansas,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, WEST MEMP...",Incident,FAA Little Rock FSDO-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,No,08-FEB-16,04-FEB-16,23:15:00Z,EASTON,Maryland,NaN,"AIRCRAFT ON LANDING, STRUCK A SIGN AND RUNWAY ...",Incident,FAA Baltimore FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,No,08-FEB-16,06-FEB-16,15:36:00Z,EUREKA,Kansas,NaN,"AIRCRAFT LANDED GEAR UP, EUREKA, KS",Incident,FAA Wichita FSDO-64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,No,08-FEB-16,06-FEB-16,14:17:00Z,EL PASO,Texas,NaN,SOUTHWEST AIRLINES FLIGHT SWA3817 BOEING 737 A...,Incident,FAA Lubbock FSDO-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,No,08-FEB-16,31-DEC-15,17:00:00Z,SAN ANTONIO,Texas,NaN,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",Accident,FAA San Antonio FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,No,08-FEB-16,05-FEB-16,11:17:00Z,MARICOPA,Arizona,NaN,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Yes,02-FEB-16,02-FEB-16,01:52:00Z,MOBILE,Alabama,NaN,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,Accident,FAA Birmingham FSDO-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
faa['ACFT_MODEL_NAME']

0           36
1          RV7
2          172
3          235
4          172
5          206
6         PA24
7          210
8          747
9          NaN
10         172
11     FIREFLY
12         310
13         210
14         T34
15         152
16    EAGLE II
17        PA34
18        PA28
19         150
20         369
21         210
22         NaN
23         737
24        GC1B
25        PA20
26        2T1A
27         560
28        BT15
29         210
        ...
53        PA28
54         150
55        CTLS
56        PA34
57      KITFOX
58         NaN
59        PA28
60        PA34
61          36
62          33
63         206
64         206
65         175
66        PA31
67          IV
68          35
69        M20K
70         500
71         310
72        M20E
73          35
74       NA265
75        M20K
76        PA24
77         737
78        O58B
79         F51
80       8KCAB
81          35
82         182
Name: ACFT_MODEL_NAME, Length: 83, dtype: object

3. Find the aircraft types and their occurrences in the dataset

In [27]:
faa.groupby('ACFT_MODEL_NAME').count()

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
ACFT_MODEL_NAME,,,,,,,,,,,,,,,,,,,,,
140,1,1,1,1,1,1,0,1,1,1,...,1,0,0,0,0,0,0,0,0,0
150,3,3,3,3,3,3,0,3,3,3,...,1,0,0,0,0,0,0,0,0,0
152,2,2,2,2,2,2,0,2,2,2,...,0,0,0,0,0,0,0,0,0,0
172,4,4,4,4,4,4,0,4,4,4,...,0,1,0,0,0,0,0,0,0,0
175,1,1,1,1,1,1,0,1,1,1,...,1,0,0,0,0,0,0,0,0,0
180,1,1,1,1,1,1,0,1,1,1,...,1,0,0,0,0,0,0,0,0,0
182,2,2,2,2,2,2,1,2,2,1,...,0,0,0,0,0,0,0,0,0,0
206,3,3,3,3,3,3,0,3,3,3,...,0,0,0,0,0,0,0,0,0,0
210,4,4,4,4,4,4,0,4,4,4,...,3,0,1,0,0,0,0,0,0,0
235,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2T1A,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
310,2,2,2,2,2,2,0,2,2,2,...,0,0,0,0,0,0,0,0,0,0
33,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
340,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
35,3,3,3,3,3,3,0,3,3,3,...,0,0,0,0,0,0,0,0,0,0
36,3,3,3,3,3,3,0,3,3,3,...,1,0,0,0,0,0,0,0,0,0
369,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
47G,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
500,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
55,1,1,1,1,1,1,0,1,1,1,...,1,0,0,0,0,0,0,0,0,0
560,1,1,1,1,1,1,0,1,1,1,...,1,0,0,0,0,0,0,0,0,0
737,2,2,2,2,2,2,0,2,2,2,...,0,0,0,0,0,0,0,0,0,0
747,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
8KCAB,2,2,2,2,2,2,0,2,2,2,...,1,0,0,0,0,0,0,0,0,0
A319,1,1,1,1,1,1,0,1,1,1,...,0,0,1,0,0,0,0,0,0,0
AA1,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
BT15,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
CTLS,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
EAGLE II,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
ERJ190,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
F51,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
FIREFLY,1,1,1,1,1,1,0,1,1,1,...,1,0,0,0,0,0,0,0,0,0
GC1B,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
GULFSTREAM200,1,1,1,1,1,1,0,1,1,1,...,1,0,0,0,0,0,0,0,0,1
IV,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
KITFOX,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
M20E,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
M20K,2,2,2,2,2,2,0,2,2,2,...,1,0,0,0,0,0,0,0,0,0
M20M,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
M4,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
NA265,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
O58B,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
PA20,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
PA24,2,2,2,2,2,2,0,2,2,2,...,0,0,0,0,0,0,0,0,0,0
PA28,3,3,3,3,3,3,1,3,3,2,...,0,0,0,1,0,0,0,0,0,0
PA31,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
PA34,3,3,3,3,3,3,0,3,3,3,...,1,0,0,0,0,0,0,0,0,0
PT19,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
RV7,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
RX8,1,1,1,1,1,1,0,1,1,1,...,1,0,1,0,0,0,0,0,0,0
S2,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
T34,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
TB21,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
TB9,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

4. Remove all the observations where aircraft names are not available

In [31]:
faa['ACFT_MODEL_NAME'].dropna(how = 'any')

0           36
1          RV7
2          172
3          235
4          172
5          206
6         PA24
7          210
8          747
10         172
11     FIREFLY
12         310
13         210
14         T34
15         152
16    EAGLE II
17        PA34
18        PA28
19         150
20         369
21         210
23         737
24        GC1B
25        PA20
26        2T1A
27         560
28        BT15
29         210
30          36
31         172
        ...
52         182
53        PA28
54         150
55        CTLS
56        PA34
57      KITFOX
59        PA28
60        PA34
61          36
62          33
63         206
64         206
65         175
66        PA31
67          IV
68          35
69        M20K
70         500
71         310
72        M20E
73          35
74       NA265
75        M20K
76        PA24
77         737
78        O58B
79         F51
80       8KCAB
81          35
82         182
Name: ACFT_MODEL_NAME, Length: 79, dtype: object

5. Display the observations where fatal flag is “Yes”

In [38]:
faa.FATAL_FLAG == 'Yes'

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22     True
23    False
24    False
25    False
26    False
27    False
28    False
29    False
      ...
53     True
54    False
55     True
56    False
57    False
58    False
59    False
60    False
61    False
62    False
63    False
64    False
65    False
66    False
67    False
68    False
69    False
70    False
71    False
72    False
73    False
74    False
75    False
76    False
77    False
78    False
79     True
80     True
81     True
82     True
Name: FATAL_FLAG, Length: 83, dtype: bool

In [39]:
faa[faa.FATAL_FLAG == 'Yes']

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,No,17-FEB-16,16-FEB-16,20:52:00Z,BUCKEYE,Arizona,NaN,"AIRCRAFT, LIGHT SPORT EVOLUTION REVO, ON TAKE...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,No,12-FEB-16,11-FEB-16,11:32:00Z,DESTIN,Florida,United States,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,Accident,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
55,No,11-FEB-16,11-FEB-16,00:17:00Z,TULARE,California,NaN,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,Accident,FAA Fresno FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,No,08-FEB-16,05-FEB-16,11:17:00Z,MARICOPA,Arizona,NaN,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Yes,02-FEB-16,02-FEB-16,01:52:00Z,MOBILE,Alabama,NaN,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,Accident,FAA Birmingham FSDO-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Assignment 4

A dataset in CSV format is given for the Fire Department of New York City. Analyze the dataset to determine:
1.	The total number of fire department facilities in New York city

In [46]:
fdny = pd.read_csv('C:/Intellipaat_python_for_datascience/lecture 6/FDNY.csv')

In [48]:
fdny.head(3)

          FacilityName     FacilityAddress    Borough
0         FacilityName     FacilityAddress    Borough
1   Engine 4/Ladder 15     42 South Street  Manhattan
2  Engine 10/Ladder 10  124 Liberty Street  Manhattan

In [65]:
fdny.drop(0 , axis = 0)

,FacilltyName,FacilityName,FacilityAddress,Borough
FacilityName,,,,
1,1,Engine 4/Ladder 15,42 South Street,Manhattan
2,2,Engine 10/Ladder 10,124 Liberty Street,Manhattan
3,3,Engine 6,49 Beekman Street,Manhattan
4,4,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan
5,5,Ladder 8,14 North Moore Street,Manhattan
6,6,Engine 9/Ladder 6,75 Canal Street,Manhattan
7,7,Engine 15/Ladder 18/Battalion 4,25 Pitt Street,Manhattan
8,8,Engine 28/Ladder 11,222 East 2nd Street,Manhattan
9,9,Engine 5,340 East 14th Street,Manhattan
10,10,Engine 55,363 Broome Street,Manhattan
11,11,Ladder 20/Division 1,253 Lafayette Street,Manhattan
12,12,Engine 24/Ladder 5/Battalion 2,227-29 6th Avenue,Manhattan
13,13,Engine 33/Ladder 9,42 Great Jones Street,Manhattan
14,14,Ladder 3/Battalion 6,108 East 13th Street,Manhattan
15,15,Squad 18,132 West 10th Street,Manhattan
16,16,Engine 34/Ladder 21,440 West 38th Street,Manhattan
17,17,Engine 26,220 West 37th Street,Manhattan
18,18,Engine 3/Ladder 12/Battalion 7,150 West 19th Street,Manhattan
19,19,Engine 1/Ladder 24,142-46 West 31st Street,Manhattan
20,20,Engine 14,14 East 18th Street,Manhattan
21,21,Engine 16 / Ladder 7,234 East 29th Street,Manhattan
22,22,Engine 21,238 East 40th Street,Manhattan
23,23,Engine 54/Ladder 4/Battalion 9,782 8th Avenue,Manhattan
24,24,Engine 23,215 West 58th Street,Manhattan
25,25,Rescue 1,530 West 43rd Street,Manhattan
26,26,Engine 40/Ladder 35,131 Amsterdam Avenue,Manhattan
27,27,Ladder 25/District Office 4/Division 3,205-207 West 77th Street,Manhattan
28,28,Engine 74,120 West 83rd Street,Manhattan
29,29,Engine 65,33 West 43rd Street,Manhattan
30,30,Engine 8 / Ladder 2 / Battalion 8,167 East 51st Street,Manhattan
...,...,...,...,...
189,189,Engine 302/Ladder 155,143-15 Rockaway Boulevard,Queens
190,190,Engine 317/Ladder 165/Battalion 54,117-11 196th Street,Queens
191,191,Engine 311/Ladder 158,145-50 Springfield Boulevard,Queens
192,192,Engine 314,142-04 Brookville Boulevard,Queens
193,193,Engine 331/Ladder 173,158-57 Cross Bay Boulevard,Queens
194,194,Engine 264/Engine 328/Ladder 134,16-15 Central Avenue,Queens
195,195,Engine 265/Ladder 121/Battalion 47 EMS Station 47,48-06 Rockaway Beach Boulevard,Queens
196,196,Engine 266/Battalion 47,92-20 Rockaway Beach Boulevard,Queens
197,197,Engine 268/Ladder 137,257 Beach 116th Street,Queens
198,198,Engine 329,402 Beach 169th Street,Queens
199,199,Marine 9,Saint George Ferry Terminal,Staten Island
200,200,Engine 155/Ladder 78,14 Brighton Avenue,Staten Island
201,201,Ladder 79/Battalion 22,1189 Castleton Avenue,Staten Island
202,202,Engine 156,412 Broadway,Staten Island
203,203,Engine 163/Ladder 83,875 Jewett Avenue,Staten Island
204,204,Engine 153/Ladder 77,74 Broad Street,Staten Island
205,205,Engine 165/Ladder 85,3067 Richmond Road,Staten Island
206,206,Engine 157/Ladder 80,1573 Castleton Avenue,Staten Island
207,207,Engine 158,65 Harbor Road,Staten Island
208,208,Engine 166/Ladder 86,1400 Richmond Avenue,Staten Island
209,209,Engine 154/District Office 8/ Staten Island Bo...,3730 Victory Boulevard,Staten Island
210,210,Engine 152/Battalion 21,256 Hylan Boulevard,Staten Island
211,211,Engine 161/Ladder 81,278 Mc Clean Avenue,Staten Island
212,212,Engine 160/Rescue 5/Division 8,1850 Clove Road,Staten Island
213,213,Engine 159,1592 Richmond Road,Staten Island
214,214,Engine 162/Ladder 82/Battalion 23,256 Nelson Avenue,Staten Island
215,215,Engine 167/Ladder 87,345 Annadale Road,Staten Island
216,216,Engine 164/Ladder 84,1560 Drumgoole Road West,Staten Island
217,217,Engine 168/EMS Station 23,1100 Rossville Avenue,Staten Island
218,218,Engine 151/Ladder 76,7219 Amboy Road,Staten Island

In [77]:
fdny['Borough'].str.contains('Manhattan').sum()

48

2.	The number of fire department facilities in each borough

In [73]:
fdny.groupby('Borough').count().FacilityName

Borough
Borough           1
Bronx            34
Brooklyn         66
Manhattan        48
Queens           50
Staten Island    20
Name: FacilityName, dtype: int64

3.	The facility names in Manhattan

In [84]:
fdny[fdny['Borough'].str.contains('Manhattan')]

,FacilltyName,FacilityName,FacilityAddress,Borough
FacilityName,,,,
1,1,Engine 4/Ladder 15,42 South Street,Manhattan
2,2,Engine 10/Ladder 10,124 Liberty Street,Manhattan
3,3,Engine 6,49 Beekman Street,Manhattan
4,4,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan
5,5,Ladder 8,14 North Moore Street,Manhattan
6,6,Engine 9/Ladder 6,75 Canal Street,Manhattan
7,7,Engine 15/Ladder 18/Battalion 4,25 Pitt Street,Manhattan
8,8,Engine 28/Ladder 11,222 East 2nd Street,Manhattan
9,9,Engine 5,340 East 14th Street,Manhattan
10,10,Engine 55,363 Broome Street,Manhattan
11,11,Ladder 20/Division 1,253 Lafayette Street,Manhattan
12,12,Engine 24/Ladder 5/Battalion 2,227-29 6th Avenue,Manhattan
13,13,Engine 33/Ladder 9,42 Great Jones Street,Manhattan
14,14,Ladder 3/Battalion 6,108 East 13th Street,Manhattan
15,15,Squad 18,132 West 10th Street,Manhattan
16,16,Engine 34/Ladder 21,440 West 38th Street,Manhattan
17,17,Engine 26,220 West 37th Street,Manhattan
18,18,Engine 3/Ladder 12/Battalion 7,150 West 19th Street,Manhattan
19,19,Engine 1/Ladder 24,142-46 West 31st Street,Manhattan
20,20,Engine 14,14 East 18th Street,Manhattan
21,21,Engine 16 / Ladder 7,234 East 29th Street,Manhattan
22,22,Engine 21,238 East 40th Street,Manhattan
23,23,Engine 54/Ladder 4/Battalion 9,782 8th Avenue,Manhattan
24,24,Engine 23,215 West 58th Street,Manhattan
25,25,Rescue 1,530 West 43rd Street,Manhattan
26,26,Engine 40/Ladder 35,131 Amsterdam Avenue,Manhattan
27,27,Ladder 25/District Office 4/Division 3,205-207 West 77th Street,Manhattan
28,28,Engine 74,120 West 83rd Street,Manhattan
29,29,Engine 65,33 West 43rd Street,Manhattan
30,30,Engine 8 / Ladder 2 / Battalion 8,167 East 51st Street,Manhattan
31,31,Engine 39/Ladder 16,157-59 East 67th Street,Manhattan
32,32,Engine 44,221 East 75th Street,Manhattan
33,33,Engine 22/Ladder 13/Battalion 10,159 East 85th Street,Manhattan
34,34,Engine 58/Ladder 26,1367 5th Avenue,Manhattan
35,35,Engine 53/Ladder 43,1836-46 3rd Avenue,Manhattan
36,36,Engine 91,242 East 111th Street,Manhattan
37,37,Engine 35/Ladder 14,2282 3rd Avenue,Manhattan
38,38,Engine 76/Ladder 22/Battalion 11,145-51 West 100th Street,Manhattan
39,39,Engine 47,502 West 113th Street,Manhattan
40,40,Engine 59/Ladder 30,111 West 133rd Street,Manhattan
41,41,Engine 37/Ladder 40,415 West 125th Street,Manhattan
42,42,Engine 69/Ladder 28/Battalion 16,248 West 143rd Street,Manhattan
43,43,Engine 80/Ladder 23,503 West 139th Street,Manhattan
44,44,Engine 84/Ladder 34,513 West 161st Street,Manhattan
45,45,Engine 67,518 West 170th Street,Manhattan
46,46,Engine 93/Ladder 45/Battalion 13,515 West 181st Street,Manhattan
47,47,Engine 95/Ladder 36,29 Vermilyea Avenue,Manhattan
48,48,Marine 1,Little West 12th Street/Hudson River,Manhattan